<<<<<<< HEAD
SELECT MEMBER_ID, MEMBER_NAME, GENDER,
DATE_FORMAT(DATE_OF_BIRTH, '%Y-%m-%d') AS DATE_OF_BIRTH
FROM MEMBER_PROFILE 
WHERE MONTH(DATE_OF_BIRTH) ='03'
AND GENDER LIKE 'W'
AND TLNO IS NOT NULL
=======
SELECT MEMBER_ID, MEMBER_NAME, GENDER,
DATE_FORMAT(DATE_OF_BIRTH, '%Y-%m-%d') AS DATE_OF_BIRTH
FROM MEMBER_PROFILE 
WHERE MONTH(DATE_OF_BIRTH) ='03'
AND GENDER LIKE 'W'
AND TLNO IS NOT NULL
>>>>>>> 71dad5660a201ca0588f83814ce552f2c3047713
ORDER BY MEMBER_ID;