<<<<<<< HEAD
-- 코드를 입력하세요
SELECT PT_NAME, PT_NO, GEND_CD, 
AGE, IFNULL(TLNO, 'NONE') AS TLNO
FROM PATIENT
WHERE AGE <= 12
AND GEND_CD LIKE 'W'
=======
-- 코드를 입력하세요
SELECT PT_NAME, PT_NO, GEND_CD, 
AGE, IFNULL(TLNO, 'NONE') AS TLNO
FROM PATIENT
WHERE AGE <= 12
AND GEND_CD LIKE 'W'
>>>>>>> 71dad5660a201ca0588f83814ce552f2c3047713
ORDER BY AGE DESC, PT_NAME;