-- 코드를 입력하세요
SELECT BO.TITLE, BO.BOARD_ID, RE.REPLY_ID, RE.WRITER_ID,RE.CONTENTS, 
DATE_FORMAT(RE.CREATED_DATE, '%Y-%m-%d') AS CREATED_DATE	
FROM USED_GOODS_BOARD BO 
INNER JOIN USED_GOODS_REPLY RE
ON BO.BOARD_ID = RE.BOARD_ID
WHERE YEAR(BO.CREATED_DATE) = 2022
AND MONTH(BO.CREATED_DATE) = 10
ORDER BY RE.CREATED_DATE, BO.TITLE;