<<<<<<< HEAD
SELECT fh.FLAVOR
FROM FIRST_HALF fh
join ICECREAM_INFO II
ON fh.FLAVOR like II.FLAVOR
where fh.TOTAL_ORDER >= 3000
AND II.INGREDIENT_TYPE like 'fruit_based'
=======
SELECT fh.FLAVOR
FROM FIRST_HALF fh
join ICECREAM_INFO II
ON fh.FLAVOR like II.FLAVOR
where fh.TOTAL_ORDER >= 3000
AND II.INGREDIENT_TYPE like 'fruit_based'
>>>>>>> 71dad5660a201ca0588f83814ce552f2c3047713
ORDER BY fh.TOTAL_ORDER DESC;