<<<<<<< HEAD
-- 코드를 입력하세요
SELECT BOOK_ID, DATE_FORMAT(PUBLISHED_DATE, '%Y-%m-%d') AS PUBLISHED_DATE
from BOOK
WHERE DATE_FORMAT(PUBLISHED_DATE, '%Y') LIKE '2021'
AND CATEGORY LIKE '인문'
=======
-- 코드를 입력하세요
SELECT BOOK_ID, DATE_FORMAT(PUBLISHED_DATE, '%Y-%m-%d') AS PUBLISHED_DATE
from BOOK
WHERE DATE_FORMAT(PUBLISHED_DATE, '%Y') LIKE '2021'
AND CATEGORY LIKE '인문'
>>>>>>> 71dad5660a201ca0588f83814ce552f2c3047713
ORDER BY PUBLISHED_DATE