<<<<<<< HEAD
SELECT DR_NAME, DR_ID,MCDP_CD,
DATE_fORMAT(HIRE_YMD, '%Y-%m-%d')
FROM DOCTOR
WHERE MCDP_CD LIKE 'CS' OR MCDP_CD LIKE 'GS'
=======
SELECT DR_NAME, DR_ID,MCDP_CD,
DATE_fORMAT(HIRE_YMD, '%Y-%m-%d')
FROM DOCTOR
WHERE MCDP_CD LIKE 'CS' OR MCDP_CD LIKE 'GS'
>>>>>>> 71dad5660a201ca0588f83814ce552f2c3047713
ORDER BY HIRE_YMD DESC, DR_NAME;